### ISSUE TITLE
Library not found

### ISSUE THREAD

**Issue by ultralKDes** [SummerWish/chrome-os-x-cookie-decryptor#1]
i failed when i build .cpp file.
error is: Library not found lnss3 lnspr4.
what did i do wrong?

**Comment by breezewish** [comment]
Thanks for your report. This is because Homebrew no longer links `nspr` and `nss` by default now.
I've just updated the README. Please follow the latest instructions there :-)

```
g++ decryptor.cpp -I/usr/local/opt/nspr/include/nspr -I/usr/local/opt/nss/include/nss -L/usr/local/opt/nspr/lib -L/usr/local/opt/nss/lib -lnspr4 -lnss3 -o decryptor
```

**Comment by ultralKDes** [comment]
I really appreciate it. I'll try it now. :)
